import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
import {FOUNDATION_LOCALES,foundationAllowlist,foundationDiff,renderTopicsIndex,extractShared,addSitemapUrl,topicsPath,includePaths} from '../scripts/foundation-migration.mjs';
import {verifyProductionCandidate} from '../scripts/production-release-guard.mjs';import {sha256} from '../scripts/deploy-boundary.mjs';
import {isApprovedPathname,PILOT_PATHNAME} from '../worker/index.mjs';
import {getIncludePath,getPublicPrefix,getSitemapPath,getTopicPath,getTopicsIndexPath,isInsideProductionRoute} from '../scripts/locale-mapping.mjs';
test('six locale foundation mappings are exact and isolated',()=>{assert.deepEqual(FOUNDATION_LOCALES,['ja','en','ko','pt','vi','zh']);assert.deepEqual(FOUNDATION_LOCALES.map(getPublicPrefix),['','/en','/ko','/pt','/vi','/zh']);assert.equal(getTopicPath('ja','foo'),'/topics/foo/');assert.equal(getTopicPath('zh','foo'),'/zh/topics/foo/');assert.equal(getTopicsIndexPath('ja'),'/topics/');assert.equal(getTopicsIndexPath('zh'),'/zh/topics/');assert.equal(getSitemapPath('ja'),'/sitemap.xml');assert.equal(getSitemapPath('zh'),'/zh/sitemap.xml');assert.equal(getIncludePath('ja','header'),'/_includes/ja/header.html');assert.equal(getIncludePath('zh','header'),'/zh/_includes/header.html');assert.equal(getIncludePath('zh','footer'),'/zh/_includes/footer.html');assert.equal(isInsideProductionRoute('zh',getIncludePath('zh','header')),true);assert.equal(isInsideProductionRoute('zh','/_includes/zh/header.html'),false);for(const l of FOUNDATION_LOCALES){const a=foundationAllowlist(l);assert.equal(new Set(a).size,a.length);if(l==='ja')assert.deepEqual(a,[]);else{assert.equal(topicsPath(l),`/${l}/topics/index.html`);assert.deepEqual(includePaths(l),[`/${l}/_includes/header.html`,`/${l}/_includes/footer.html`]);assert.equal(a.length,4);}}});
test('topics index has SEO, breadcrumb, navigation and no unpublished Topic link',()=>{for(const l of FOUNDATION_LOCALES){const html=renderTopicsIndex(l,'<header class="site-header"><nav>N</nav></header>','<footer class="site-footer">F</footer>');for(const token of ['<title>','description','canonical','robots','<h1','breadcrumb','<header','<footer','<nav'])assert.match(html,new RegExp(token));assert.doesNotMatch(html,/promotion-demo/);}});
test('shared includes are extracted by locale foundation without cross-locale substitution',()=>{const html='<header class="site-header">H</header><main>M</main><footer class="site-footer">F</footer>';assert.equal(extractShared(html,'header'),'<header class="site-header">H</header>\n');assert.equal(extractShared(html,'footer'),'<footer class="site-footer">F</footer>\n');});
test('sitemap foundation addition is exact and idempotent',()=>{const a=addSitemapUrl('<urlset>\n</urlset>','https://mnp-navi.jp/en/topics/');assert.equal((a.match(/en\/topics/g)||[]).length,1);assert.equal(addSitemapUrl(a,'https://mnp-navi.jp/en/topics/'),a);});
test('foundation diff accepts exact paths and rejects shop, guide, other Topic and deletion',()=>{const before={'/index.html':{sha256:'a',size:1}},after={...before,'/en/topics/index.html':{sha256:'b',size:1}};assert.equal(foundationDiff(before,after,['/en/topics/index.html']).added.length,1);for(const key of ['/shop/x/index.html','/guide/x/index.html','/en/topics/other/index.html'])assert.throws(()=>foundationDiff(before,{...after,[key]:{sha256:'x',size:1}},['/en/topics/index.html']));assert.throws(()=>foundationDiff(before,{},[]));});
test('Worker authorizes only exact manifest-derived pathname and retains Japanese P0',()=>{const env={LOCALE:'en',APPROVED_PROMOTION_PATHNAME:'/en/topics/promo/'};for(const bad of ['/en/topics/','/en/topics/promo','/en/topics/promo/x','/en/topics/promo-extra/','//en/topics/promo/'])assert.equal(isApprovedPathname(bad,env),false);assert.equal(isApprovedPathname('/en/topics/promo/',env),true);assert.equal(isApprovedPathname(PILOT_PATHNAME,{LOCALE:'ja'}),true);assert.equal(isApprovedPathname(PILOT_PATHNAME,env),false);});
test('guard rejects expanded foundation allowlist, deletion, drift, cross locale and promotion over-limit',async t=>{const dir=await mkdtemp(path.join(tmpdir(),'foundation-'));t.after(()=>rm(dir,{recursive:true,force:true}));await mkdir(path.join(dir,'en','topics'),{recursive:true});await writeFile(path.join(dir,'en','topics','index.html'),'x');const base={schema:1,kind:'foundation',locale:'en',worker:'rm-referral-en',config:'wrangler.en.jsonc',candidateFileCount:1,allowedChangedPaths:['/en/topics/index.html'],added:['/en/topics/index.html'],changed:[],deleted:[],approvedPathname:null};const {inventorySha256}=await import('../scripts/promotion-release.mjs');const {inventory}=await import('../scripts/deploy-boundary.mjs');base.candidateInventorySha256=inventorySha256(await inventory(dir));const hash=p=>sha256(Buffer.from(JSON.stringify(p)));await assert.doesNotReject(()=>verifyProductionCandidate({plan:base,approvedPlanSha256:hash(base),candidate:dir,config:'wrangler.en.jsonc',locale:'en'}));for(const mutate of [p=>p.deleted=['/x'],p=>p.added=['/shop/x'],p=>p.locale='ko',p=>p.candidateInventorySha256='0'.repeat(64)]){const p=structuredClone(base);mutate(p);await assert.rejects(()=>verifyProductionCandidate({plan:p,approvedPlanSha256:hash(p),candidate:dir,config:'wrangler.en.jsonc',locale:'en'}));}const p={...base,kind:'promotion',approvedPathname:'/en/topics/x/',changed:['/en/topics/x/index.html','/en/sitemap.xml','/shop/x'],added:[],allowedChangedPaths:['/en/topics/x/index.html','/en/sitemap.xml','/shop/x']};await assert.rejects(()=>verifyProductionCandidate({plan:p,approvedPlanSha256:hash(p),candidate:dir,config:'wrangler.en.jsonc',locale:'en'}));});

test('promotion guard accepts truthful new/update diffs and rejects boundary expansion',async t=>{
 const {inventorySha256,topicMapping}=await import('../scripts/promotion-release.mjs');const {inventory}=await import('../scripts/deploy-boundary.mjs');const hash=p=>sha256(Buffer.from(JSON.stringify(p)));
 async function fixture(locale='en',mode='added',sitemap=false){const m=topicMapping(locale,'new-topic'),dir=await mkdtemp(path.join(tmpdir(),'promotion-guard-'));t.after(()=>rm(dir,{recursive:true,force:true}));for(const [asset,body] of [[m.assetPath,'topic'],[m.sitemapAssetPath,'sitemap']]){const f=path.join(dir,asset.slice(1));await mkdir(path.dirname(f),{recursive:true});await writeFile(f,body);}const files=await inventory(dir),added=mode==='added'?[m.assetPath]:[],changed=mode==='changed'?[m.assetPath]:[];if(sitemap)changed.push(m.sitemapAssetPath);const plan={schema:1,kind:'promotion',locale,worker:locale==='ja'?'rm-referral':`rm-referral-${locale}`,config:locale==='ja'?'wrangler.jsonc':`wrangler.${locale}.jsonc`,slug:'new-topic',assetPath:m.assetPath,sitemapAssetPath:m.sitemapAssetPath,candidateFileCount:Object.keys(files).length,candidateInventorySha256:inventorySha256(files),allowedChangedPaths:[m.assetPath,...(sitemap?[m.sitemapAssetPath]:[])],added,changed,deleted:[],unexpected:[],approvedPathname:m.pathname};return {m,dir,plan,run:p=>verifyProductionCandidate({plan:p,approvedPlanSha256:hash(p),candidate:dir,config:p.config,locale:p.locale})};}
 for(const [name,locale,mode,sitemap] of [['new Topic added only','en','added',false],['new Topic added plus sitemap','en','added',true],['existing Topic changed only','en','changed',false],['existing Topic changed plus sitemap','en','changed',true],['JA new Topic plus canonical sitemap','ja','added',true],['foreign new Topic plus locale sitemap','zh','added',true]])await t.test(name,async()=>{const f=await fixture(locale,mode,sitemap);await assert.doesNotReject(()=>f.run(f.plan));});
 const rejected=[
  ['target added and changed',p=>p.changed.unshift(p.assetPath)],['two Topics',p=>p.added.push(p.assetPath.replace('new-topic','other-topic'))],['other Topic',p=>p.changed.push(p.assetPath.replace('new-topic','other-topic'))],['Topics index',p=>p.changed.push('/en/topics/index.html')],['shared include',p=>p.changed.push('/en/_includes/header.html')],['shop',p=>p.changed.push('/en/shop/x/index.html')],['guide',p=>p.changed.push('/en/guide/x/index.html')],['CSS',p=>p.changed.push('/en/css/x.css')],['JavaScript',p=>p.changed.push('/en/js/x.js')],['image',p=>p.changed.push('/en/images/x.webp')],['font',p=>p.changed.push('/en/fonts/x.woff2')],['robots',p=>p.changed.push('/en/robots.txt')],['root',p=>p.changed.push('/en/index.html')],['deletion',p=>p.deleted.push(p.assetPath)],['wrong sitemap',p=>p.changed.push('/ko/sitemap.xml')],['two sitemaps',p=>p.changed.push('/en/sitemap.xml','/ko/sitemap.xml')],['prefix collision',p=>p.assetPath='/en/topics/new-topic-extra/index.html'],['suffix collision',p=>p.approvedPathname='/en/topics/x-new-topic/'],['missing index',p=>p.assetPath='/en/topics/new-topic/page.html'],['wrong locale Topic',p=>p.assetPath='/ko/topics/new-topic/index.html'],['JA namespace',p=>{p.locale='ja';p.worker='rm-referral';p.config='wrangler.jsonc';p.approvedPathname='/ja/topics/new-topic/';p.assetPath='/ja/topics/new-topic/index.html';p.sitemapAssetPath='/sitemap.xml';}],['encoded collision',p=>p.approvedPathname='/en/topics/new%2Dtopic/']];
 for(const [name,mutate] of rejected)await t.test('reject '+name,async()=>{const f=await fixture();const p=structuredClone(f.plan);mutate(p);p.allowedChangedPaths=[...new Set([...(p.added??[]),...(p.changed??[])])];await assert.rejects(()=>f.run(p));});
});
