import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256} from '../scripts/deploy-boundary.mjs';
import {PROMOTION_LOCALES,topicMapping,manifestSha256} from '../scripts/promotion-release.mjs';
import {LOCALE_RUNTIME,productionPlanSha256,validateProductionReleasePlan,compileApprovedPromotionRoutes,isApprovedPromotionRequest,evaluatePromotionState} from '../scripts/promotion-production.mjs';
import {publicationStateSha256} from '../scripts/publication-state-node.mjs';

const hash=value=>sha256(String(value));
function fixture(){
 const locales={};for(const locale of PROMOTION_LOCALES){const m=topicMapping(locale,'promo');locales[locale]={source:m.source,pathname:m.pathname,assetPath:m.assetPath,sitemapAssetPath:m.sitemapAssetPath,sourceSha256:hash(locale+' source'),targetSha256:hash(locale+' target'),baselineReceiptSha256:hash(locale+' receipt'),baselineAttestationSha256:hash(locale+' attestation')};}
 const manifest={schema:1,promotionId:'promo',slug:'promo',locales};
 const publicationState={schema:1,promotionId:'promo',slug:'promo',currentLocale:'zh',locales:Object.fromEntries(PROMOTION_LOCALES.map(locale=>[locale,{locale,status:locale==='zh'?'CURRENT_RELEASE_CANDIDATE':'UNPUBLISHED',pathname:topicMapping(locale,'promo').pathname,bindingSource:'test'}]))};
 const plan={schema:1,promotionId:'promo',manifestSha256:manifestSha256(manifest),createdAt:'2026-09-25T00:00:00Z',publicationState,publicationStateSha256:publicationStateSha256(publicationState),locales:{}};
 for(const locale of PROMOTION_LOCALES){const m=topicMapping(locale,'promo'),sitemapBefore=hash(locale+' sitemap before'),sitemapAfter=locale==='ja'?hash(locale+' sitemap after'):sitemapBefore;plan.locales[locale]={pathname:m.pathname,assetPath:m.assetPath,sitemapPath:m.sitemapAssetPath,worker:LOCALE_RUNTIME[locale].worker,config:LOCALE_RUNTIME[locale].config,baselineArtifactSha256:hash(locale+' artifact'),baselineReceiptSha256:locales[locale].baselineReceiptSha256,baselineAttestationSha256:locales[locale].baselineAttestationSha256,candidateInventorySha256:hash(locale+' candidate'),targetSha256:locales[locale].targetSha256,sitemapBeforeSha256:sitemapBefore,sitemapAfterSha256:sitemapAfter,expectedCurrentVersionId:locale+'-current',rollbackVersionId:locale+'-rollback',allowedChangedPaths:[m.assetPath,...(sitemapBefore===sitemapAfter?[]:[m.sitemapAssetPath])],allowedDeletedPaths:[]};}
 return {manifest,plan};
}

test('release plan binds six independent locale production boundaries',()=>{const f=fixture();const result=validateProductionReleasePlan(f.plan,f.manifest,{approvedPlanSha256:productionPlanSha256(f.plan)});assert.match(result.releasePlanSha256,/^[0-9a-f]{64}$/);for(const locale of PROMOTION_LOCALES){const next=PROMOTION_LOCALES[(PROMOTION_LOCALES.indexOf(locale)+1)%PROMOTION_LOCALES.length];assert.notEqual(f.plan.locales[locale].expectedCurrentVersionId,f.plan.locales[next].expectedCurrentVersionId);}});
test('release plan mutation, locale/config drift, baseline drift and expanded allowlist fail closed',()=>{for(const mutate of [f=>f.plan.createdAt='bad',f=>f.plan.manifestSha256=hash('wrong'),f=>f.plan.locales.en.config='wrangler.jsonc',f=>f.plan.locales.ko.baselineReceiptSha256=hash('wrong'),f=>f.plan.locales.pt.allowedChangedPaths.push('/shop/x/index.html'),f=>f.plan.locales.vi.allowedDeletedPaths.push('/index.html')]){const f=fixture();mutate(f);assert.throws(()=>validateProductionReleasePlan(f.plan,f.manifest),/Plan|mapping|binding|allowlist/);}});
test('approved route set accepts exact manifest pathnames only',()=>{const f=fixture(),routes=compileApprovedPromotionRoutes(f.manifest,f.plan);for(const locale of PROMOTION_LOCALES){const exact=topicMapping(locale,'promo').pathname;assert.equal(isApprovedPromotionRequest('https://mnp-navi.jp'+exact,locale,routes),true);for(const rejected of ['/','/topics/','/topics/random/','/guide/promo/','/shop/promo/',exact.slice(0,-1),exact+'extra',exact.replace('/promo/','/promo-extra/'),exact+'%2e%2e/','/%2e%2e/topics/promo/','//topics/promo/'])assert.equal(isApprovedPromotionRequest('https://mnp-navi.jp'+rejected,locale,routes),false,rejected);const other=locale==='ja'?'en':'ja';assert.equal(isApprovedPromotionRequest('https://mnp-navi.jp'+exact,other,routes),false);}}
);
test('query cannot turn an unapproved pathname into an approved route',()=>{const f=fixture(),routes=compileApprovedPromotionRoutes(f.manifest,f.plan);assert.equal(isApprovedPromotionRequest('https://mnp-navi.jp/?pathname=/topics/promo/','ja',routes),false);assert.equal(isApprovedPromotionRequest('https://mnp-navi.jp/topics/promo/?preview=1','ja',routes),true);});
test('partial failure stops only the failed locale and never rolls back all locales automatically',()=>{const states=Object.fromEntries(PROMOTION_LOCALES.map(locale=>[locale,'VERSION_VERIFIED']));states.ko='FAILED_BEFORE_PRODUCTION';assert.deepEqual(evaluatePromotionState(states),{continueRelease:false,automaticRollback:[],blockedLocales:['ko'],coordinatorDecisionRequired:false});states.ko='VERSION_VERIFIED';states.en='FAILED_AFTER_PRODUCTION';assert.deepEqual(evaluatePromotionState(states),{continueRelease:false,automaticRollback:['en'],blockedLocales:[],coordinatorDecisionRequired:false});const semantic=evaluatePromotionState(states,{crossLocaleSemanticFailure:true});assert.equal(semantic.coordinatorDecisionRequired,true);assert.deepEqual(semantic.automaticRollback,[]);});
