import test from 'node:test';
import assert from 'node:assert/strict';
import {sha256} from '../scripts/deploy-boundary.mjs';
import {verifyAsset,verifyInventory} from '../scripts/verify-known-production-paths.mjs';
import {CANONICAL_LOCALES,getIncludePath,getTopicPath} from '../scripts/locale-mapping.mjs';
import {RETAINED_JA_P0_PATHNAME,transformHeaderInclude,transformPromotionEdgeResponse,transformRetainedJaP0EdgeResponse,validatePromotionStaticPublication,validatePublicationState,visiblePromotionLocales} from '../scripts/promotion-edge-response.mjs';
import {publicationStateSha256} from '../scripts/publication-state-node.mjs';

const slug='promotion-release-validation',promotionId=slug;
function state(currentLocale='zh',published=[]){return {schema:1,promotionId,slug,currentLocale,locales:Object.fromEntries(CANONICAL_LOCALES.map(locale=>[locale,{locale,status:locale===currentLocale?'CURRENT_RELEASE_CANDIDATE':published.includes(locale)?'PRODUCTION_VERIFIED':'UNPUBLISHED',pathname:getTopicPath(locale,slug),bindingSource:'test'}]))};}
function staticHtml(locale='zh',locales=[locale]){const links=locales.map(value=>`<link rel="alternate" href="https://mnp-navi.jp${getTopicPath(value,slug)}">`).join('');return `${links}<rm-include src="${getIncludePath(locale,'header')}" data-locales="${locales.join(',')}" data-header-label="Promotion"><i>fallback</i></rm-include><main>body</main><rm-include src="${getIncludePath(locale,'footer')}"><i>fallback</i></rm-include>`;}
const header='<header><a class="header-link">Home</a><select><option value="/guide/replacement-program/">JA</option><option value="/en/guide/replacement-program/">EN</option><option value="/zh/guide/replacement-program/">ZH</option><option value="/ko/guide/replacement-program/">KO</option><option value="/vi/guide/replacement-program/">VI</option><option value="/pt/guide/replacement-program/">PT</option></select></header>';
const footer='<footer>Footer</footer>';
const response=bytes=>new Response(bytes,{status:200,headers:{'content-type':'text/html'}});

test('Publication State hash is deterministic',()=>assert.equal(publicationStateSha256(state()),publicationStateSha256(structuredClone(state()))));
test('Publication State requires exactly six canonical locales',()=>{const value=state();delete value.locales.en;assert.throws(()=>validatePublicationState(value,{promotionId,slug,currentLocale:'zh'}),/six locales/);});
test('Publication State requires one current candidate',()=>{const value=state();value.locales.zh.status='UNPUBLISHED';assert.throws(()=>validatePublicationState(value,{promotionId,slug,currentLocale:'zh'}),/Exactly one/);});
test('Publication State rejects a candidate in another locale',()=>{const value=state();value.locales.en.status='CURRENT_RELEASE_CANDIDATE';assert.throws(()=>validatePublicationState(value,{promotionId,slug,currentLocale:'zh'}),/candidate locale|Exactly one/);});
test('zero published locales exposes current candidate only',()=>assert.deepEqual(visiblePromotionLocales(state(),{promotionId,slug,currentLocale:'zh'}),['zh']));
test('one published locale plus current candidate is visible',()=>assert.deepEqual(visiblePromotionLocales(state('en',['zh']),{promotionId,slug,currentLocale:'en'}),['en','zh']));
test('two published locales plus current candidate are visible in canonical order',()=>assert.deepEqual(visiblePromotionLocales(state('ko',['zh','en']),{promotionId,slug,currentLocale:'ko'}),['en','ko','zh']));
test('all six locales can be represented without ambiguity',()=>assert.deepEqual(visiblePromotionLocales(state('zh',['ja','en','ko','pt','vi']),{promotionId,slug,currentLocale:'zh'}),CANONICAL_LOCALES));
test('VERSION_UPLOADED is not publicly visible',()=>{const value=state();value.locales.en.status='VERSION_UPLOADED';assert.deepEqual(visiblePromotionLocales(value,{promotionId,slug,currentLocale:'zh'}),['zh']);});
test('PRODUCTION_FAILED is not publicly visible',()=>{const value=state();value.locales.en.status='PRODUCTION_FAILED';assert.deepEqual(visiblePromotionLocales(value,{promotionId,slug,currentLocale:'zh'}),['zh']);});
test('ROLLED_BACK is not publicly visible',()=>{const value=state();value.locales.en.status='ROLLED_BACK';assert.deepEqual(visiblePromotionLocales(value,{promotionId,slug,currentLocale:'zh'}),['zh']);});
test('Japanese publication path retains empty public prefix',()=>assert.equal(state('ja').locales.ja.pathname,'/topics/promotion-release-validation/'));
test('/ja/ publication path is rejected',()=>{const value=state('ja');value.locales.ja.pathname='/ja/topics/promotion-release-validation/';assert.throws(()=>validatePublicationState(value,{promotionId,slug,currentLocale:'ja'}),/ja Publication State mismatch/);});
test('static publication binding accepts current locale only',()=>assert.deepEqual(validatePromotionStaticPublication({html:staticHtml(),locale:'zh',slug,publicationState:state(),promotionId}).publicationLocales,['zh']));
test('static publication binding rejects unpublished hreflang',()=>assert.throws(()=>validatePromotionStaticPublication({html:staticHtml('zh',['zh','en']),locale:'zh',slug,publicationState:state(),promotionId}),/binding mismatch|hreflang/));
test('static publication binding rejects missing published hreflang',()=>assert.throws(()=>validatePromotionStaticPublication({html:staticHtml('en',['en']),locale:'en',slug,publicationState:state('en',['zh']),promotionId}),/binding mismatch|hreflang/));
test('static publication binding rejects /ja/ contamination',()=>assert.throws(()=>validatePromotionStaticPublication({html:staticHtml()+'<a href="/ja/topics/x/">x</a>',locale:'zh',slug,publicationState:state(),promotionId}),/\/ja\//));
test('selector removes unpublished locales',()=>{const html=transformHeaderInclude({html:header,locale:'zh',pathname:getTopicPath('zh',slug),publicationLocales:['zh'],label:'Promotion'});assert.match(html,/\/zh\/topics\/promotion-release-validation\//);for(const locale of ['en','ko','pt','vi'])assert.doesNotMatch(html,new RegExp(`/${locale}/topics/`));assert.doesNotMatch(html,/value="\/topics\//);});
test('selector retains published and current locales only',()=>{const html=transformHeaderInclude({html:header,locale:'en',pathname:getTopicPath('en',slug),publicationLocales:['en','zh'],label:'Promotion'});assert.match(html,/\/en\/topics\//);assert.match(html,/\/zh\/topics\//);assert.doesNotMatch(html,/\/ko\/topics\//);});
test('deterministic edge transform replaces both include wrappers',()=>{const transformed=transformPromotionEdgeResponse({staticHtml:staticHtml(),locale:'zh',pathname:getTopicPath('zh',slug),headerHtml:header,footerHtml:footer,publicationState:state(),promotionId,slug});assert.match(transformed,/<header>/);assert.match(transformed,/<footer>/);assert.doesNotMatch(transformed,/<rm-include/);});
test('edge transform rejects wrong include route',()=>assert.throws(()=>transformPromotionEdgeResponse({staticHtml:staticHtml().replace('/zh/_includes/header.html','/_includes/zh/header.html'),locale:'zh',pathname:getTopicPath('zh',slug),headerHtml:header,footerHtml:footer,publicationState:state(),promotionId,slug}),/header include/));
test('edge transform rejects an unauthorized pathname',()=>assert.throws(()=>transformPromotionEdgeResponse({staticHtml:staticHtml(),locale:'zh',pathname:'/zh/topics/other/',headerHtml:header,footerHtml:footer,publicationState:state(),promotionId,slug}),/Authorized pathname/));
test('retained JA P0 route has a deterministic independent edge identity',()=>{const transformed=transformRetainedJaP0EdgeResponse({staticHtml:staticHtml('ja',['ja']),locale:'ja',pathname:RETAINED_JA_P0_PATHNAME,headerHtml:header,footerHtml:footer});assert.match(transformed,/<header>/);assert.match(transformed,/<footer>/);assert.doesNotMatch(transformed,/<rm-include/);assert.match(transformed,/value="\/guide\/rakuten-mobile-three-features\/"/);});
test('retained JA P0 transform rejects non-exact route variants',()=>{for(const pathname of ['/guide/rakuten-mobile-three-features','/guide/rakuten-mobile-three-features/x/','/guide/prefix-rakuten-mobile-three-features/','/guide/rakuten-mobile-three-features%2f/','//guide/rakuten-mobile-three-features/'])assert.throws(()=>transformRetainedJaP0EdgeResponse({staticHtml:staticHtml('ja',['ja']),locale:'ja',pathname,headerHtml:header,footerHtml:footer}),/exact pathname/);});
test('retained JA P0 transform rejects foreign locale and expanded locale set',()=>{assert.throws(()=>transformRetainedJaP0EdgeResponse({staticHtml:staticHtml('ja',['ja']),locale:'en',pathname:RETAINED_JA_P0_PATHNAME,headerHtml:header,footerHtml:footer}),/exact pathname/);assert.throws(()=>transformRetainedJaP0EdgeResponse({staticHtml:staticHtml('ja',['ja','en']),locale:'ja',pathname:RETAINED_JA_P0_PATHNAME,headerHtml:header,footerHtml:footer}),/locale binding/);});
test('non-target static verification remains byte exact',async()=>{const bytes=Buffer.from('static');const result=await verifyAsset({assetPath:'/zh/a.css',expected:{size:bytes.length,sha256:sha256(bytes)},baseUrl:'https://example.test',fetchImpl:async()=>response(bytes)});assert.equal(result.result,'MATCH');assert.equal(result.transformation,'STATIC');});
test('target edge verification accepts deterministic transformed bytes',async()=>{const staticBytes=Buffer.from('static'),edgeBytes=Buffer.from('edge');const result=await verifyAsset({assetPath:'/zh/topics/x/index.html',expected:{size:staticBytes.length,sha256:sha256(staticBytes)},expectedResponse:{bytes:edgeBytes,transformation:'HTML_REWRITER_V1'},baseUrl:'https://example.test',fetchImpl:async()=>response(edgeBytes)});assert.equal(result.result,'MATCH');assert.equal(result.staticExpectedSha256,sha256(staticBytes));assert.equal(result.expectedSha256,sha256(edgeBytes));});
test('declared transformed expected SHA mismatch is rejected',async()=>{const edgeBytes=Buffer.from('edge');await assert.rejects(()=>verifyAsset({assetPath:'/zh/topics/x/index.html',expected:{size:1,sha256:'0'.repeat(64)},expectedResponse:{bytes:edgeBytes,sha256:'0'.repeat(64),transformation:'HTML_REWRITER_V1'},baseUrl:'https://example.test',fetchImpl:async()=>response(edgeBytes)}),/expected response identity mismatch/);});
test('target edge verification distinguishes static and transformed expectation',async()=>{const staticBytes=Buffer.from('static'),edgeBytes=Buffer.from('edge');const result=await verifyAsset({assetPath:'/zh/topics/x/index.html',expected:{size:staticBytes.length,sha256:sha256(staticBytes)},expectedResponse:{bytes:edgeBytes,transformation:'HTML_REWRITER_V1'},baseUrl:'https://example.test',fetchImpl:async()=>response(staticBytes)});assert.equal(result.result,'MISMATCH');assert.notEqual(result.staticExpectedSha256,result.expectedSha256);});
test('unexpected target mutation is rejected',async()=>{const expected=Buffer.from('edge'),actual=Buffer.from('mutated');const result=await verifyAsset({assetPath:'/zh/topics/x/index.html',expected:{size:1,sha256:'0'.repeat(64)},expectedResponse:{bytes:expected,transformation:'HTML_REWRITER_V1'},baseUrl:'https://example.test',fetchImpl:async()=>response(actual)});assert.equal(result.result,'MISMATCH');});
test('inventory transformation map applies only to exact target asset',async()=>{const files={'/zh/topics/x/index.html':{size:6,sha256:sha256(Buffer.from('static'))},'/zh/a.css':{size:3,sha256:sha256(Buffer.from('css'))}};const results=await verifyInventory({files,baseUrl:'https://example.test',edgeResponses:{'/zh/topics/x/index.html':{bytes:Buffer.from('edge'),transformation:'HTML_REWRITER_V1'}},fetchImpl:async url=>response(url.includes('/topics/x/')?Buffer.from('edge'):Buffer.from('css')),concurrency:1});assert.equal(results[0].transformation,'STATIC');assert.equal(results[1].transformation,'HTML_REWRITER_V1');assert.ok(results.every(item=>item.result==='MATCH'));});
test('inventory supports independent promotion and retained P0 edge identities only',async()=>{const files={'/topics/x/index.html':{size:6,sha256:sha256(Buffer.from('static'))},'/guide/rakuten-mobile-three-features/index.html':{size:9,sha256:sha256(Buffer.from('p0-static'))},'/a.css':{size:3,sha256:sha256(Buffer.from('css'))}};const edgeResponses={'/topics/x/index.html':{bytes:Buffer.from('promotion-edge'),transformation:'PROMOTION_HTML_REWRITER_V1'},'/guide/rakuten-mobile-three-features/index.html':{bytes:Buffer.from('p0-edge'),transformation:'RETAINED_JA_P0_HTML_REWRITER_V1'}};const results=await verifyInventory({files,baseUrl:'https://example.test',edgeResponses,fetchImpl:async url=>response(url.includes('/topics/x/')?Buffer.from('promotion-edge'):url.includes('rakuten-mobile-three-features')?Buffer.from('p0-edge'):Buffer.from('css')),concurrency:1});assert.equal(results.filter(item=>item.transformation==='STATIC').length,1);assert.equal(results.filter(item=>item.transformation!=='STATIC').length,2);assert.ok(results.every(item=>item.result==='MATCH'));});
