import {cp, mkdir, readdir, readFile, rm, writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {readSource, key, root} from './page-sources.mjs';

const usage = 'Usage: npm run build:page -- <locale/route> [--output <dir>]';
const argv = process.argv.slice(2);
const wrangler = argv.includes('--wrangler');
const positional = argv.filter(a => a !== '--wrangler');
const requested = process.env.RM_PAGE || positional[0];
if (!requested) throw new Error(`${usage}. RM_PAGE is required for the Wrangler build hook; it never falls back to a full build.`);
const normalized = requested.replace(/^\/+|\/+$/g, '');
const [locale, ...routeParts] = normalized.split('/');
const route = routeParts.join('/');
if (!locale || !route) throw new Error(`Invalid page: ${requested}. Use locale/route, for example ja/guide/rakuten-mobile-three-features`);
const source = readSource(locale, route);
const expected = key(locale, route);
const staging = path.join(root, '.single-page-build');
const singleSrc = path.join(root, '.single-page-source');
const outputArg = positional.indexOf('--output');
const output = path.resolve(root, process.env.RM_PAGE_OUTPUT || (outputArg >= 0 ? positional[outputArg + 1] : (wrangler ? '.deploy/ja' : '.single-page-output')));
// Wrangler's assets directory is already locale-scoped (.deploy/{locale}); keep
// the generated artifact route-scoped for both the Japanese and language configs.
const targetRel = path.join(route, 'index.html');
const target = path.join(staging, targetRel);
const outputTarget = path.join(output, targetRel);

await rm(staging, {recursive: true, force: true});
await rm(singleSrc, {recursive: true, force: true});
await mkdir(path.join(singleSrc, 'pages'), {recursive: true});
const component = path.join(root, 'astro-site/src/components/ContentPage.astro');
await writeFile(path.join(singleSrc, 'pages/index.astro'), `---\nimport ContentPage from ${JSON.stringify(component)};\n---\n<ContentPage locale=${JSON.stringify(locale)} route=${JSON.stringify(route)} />\n`);
await rm(outputTarget, {force: true});
await mkdir(output, {recursive: true});
const env = {...process.env, RM_SINGLE_PAGE: expected, RM_SINGLE_SRC: singleSrc, RM_SINGLE_OUT: staging, ASTRO_TELEMETRY_DISABLED: '1'};
const started = performance.now();
const result = spawnSync('npm', ['--prefix', 'astro-site', 'run', 'build'], {cwd: root, env, stdio: 'inherit'});
if (result.status !== 0) throw new Error(`Single-page Astro generation failed (${result.status})`);
const builtTarget = path.join(staging, 'index.html');
if (!existsSync(builtTarget)) throw new Error('Expected single output not found: index.html');
await mkdir(path.dirname(outputTarget), {recursive: true});
await cp(builtTarget, outputTarget);
const html = await readFile(outputTarget, 'utf8');
if (!html.includes('<meta name="rm-layout" content="shared-v1"')) throw new Error('Output is not generated by BaseLayout');
if ((html.match(/<main\b/g) || []).length !== 1) throw new Error('Expected exactly one main element');
const files = [];
async function collect(dir) { for (const e of await readdir(dir, {withFileTypes:true})) { const f=path.join(dir,e.name); if(e.isDirectory()) await collect(f); else files.push(path.relative(staging,f)); } }
await collect(staging);
console.log(JSON.stringify({page: expected, source: path.relative(root, path.join(root,'content/pages',locale,route,'page.json')), output: path.relative(root, outputTarget), generatedHtml: 1, stagingFiles: files.length, durationMs: Math.round(performance.now()-started), fullBuild: false}));
await rm(staging, {recursive: true, force: true});
await rm(singleSrc, {recursive: true, force: true});
