import {readdir,readFile,writeFile,mkdir,rm,cp,stat} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {root,locales,hash,verifyFrozen,routes} from './page-sources.mjs';
import {localizeNavigation} from './localize-navigation.mjs';
const dist=path.join(root,'astro-site/dist'),release=path.join(root,'.deploy'),receiptFile=path.join(release,'release.json');
export async function walk(dir){let out=[];for(const e of await readdir(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(f));else if(e.isFile())out.push(f);else throw new Error('Unsupported symlink in release source: '+f);}return out.sort();}
export async function fingerprint(){
 const files=[];for(const dir of ['astro-site/src','astro-site/scripts','astro-site/tests','scripts','content','css','js'])files.push(...await walk(path.join(root,dir)));
 for(const name of ['local-topics.json','rakuten-base-stations.json','rakuten-shops-geocoded.csv','value-carrier-shops-geocoded.csv',...['hokkaido','aomori','iwate','miyagi','akita','yamagata','fukushima','niigata','tochigi','gunma','ibaraki','saitama','chiba','tokyo','kanagawa','nagano','yamanashi','toyama','ishikawa','fukui','shizuoka','aichi','gifu','mie','shiga','kyoto','osaka','hyogo','nara','wakayama','tottori','shimane','okayama','hiroshima','yamaguchi','tokushima','kagawa','ehime','kochi','fukuoka','saga','nagasaki','kumamoto','oita','miyazaki','kagoshima','okinawa'].map(slug=>slug==='hokkaido'?'carrier-shops-geocoded.csv':slug+'-carrier-shops-geocoded.csv')])files.push(path.join(root,'data',name));
 for(const dir of ['images','astro-site/public/images',...locales.filter(l=>l!=='ja').map(l=>'astro-site/public/'+l+'/images')])if(existsSync(path.join(root,dir)))files.push(...await walk(path.join(root,dir)));
 for(const prefix of ['',...locales.filter(l=>l!=='ja').map(l=>l+'/')])for(const name of ['robots.txt','sitemap.xml','google55b1c42743aa7ee2.html']){const f=path.join(root,prefix+name);if(existsSync(f))files.push(f);}
 for(const file of ['package.json','package-lock.json','astro-site/package.json','astro-site/package-lock.json','astro-site/astro.config.mjs',...locales.map(l=>'wrangler'+(l==='ja'?'':'.'+l)+'.jsonc')])files.push(path.join(root,file));
 return hash((await Promise.all(files.sort().map(async f=>path.relative(root,f)+':'+hash(await readFile(f))))).join('\n'));
}
export function assertShared(html,label){
 if(!/<meta\s+name="rm-layout"\s+content="shared-v1"/.test(html))throw new Error('Not generated by BaseLayout: '+label);
 const classes=[...html.matchAll(/class="([^"]*)"/g)].map(m=>m[1].split(/\s+/));
 for(const cls of ['site-header','site-footer'])if(classes.filter(tokens=>tokens.includes(cls)).length!==1)throw new Error('Expected one shared '+cls+': '+label);
}
export async function verifyReceipt(expected){
 const r=JSON.parse(await readFile(receiptFile,'utf8'));if(r.version!==1||r.input!==expected)throw new Error('Release is stale: build shared components again');
 for(const l of locales){const base=path.join(release,l);const actual=await walk(base);if(actual.length!==r.files[l].length)throw new Error('Release file count changed: '+l);
  for(const item of r.files[l]){const f=path.join(base,item.file);if(!f.startsWith(base+path.sep))throw new Error('Invalid receipt path');const b=await readFile(f);if(hash(b)!==item.sha256)throw new Error('Release was edited: '+f);}
 }return r;
}
function run(command,args){const r=spawnSync(command,args,{cwd:root,stdio:'inherit',env:{...process.env,NODE_OPTIONS:(process.env.NODE_OPTIONS||'')+' --max-old-space-size=6144',ASTRO_TELEMETRY_DISABLED:'1'}});if(r.status!==0)throw new Error(command+' failed ('+r.status+')');}
export async function prepareRelease(){
 verifyFrozen();const input=await fingerprint();
 try{await verifyReceipt(input);console.log('Verified current shared-component release.');return;}catch(e){console.log('Building a fresh shared-component release: '+e.message);}
 const lock=path.join(root,'.release-lock');await mkdir(lock).catch(()=>{throw new Error('Another release is running. Do not bypass the build guard.');});
 try{
  await rm(receiptFile,{force:true});
  run('npm',['--prefix','astro-site','ci','--ignore-scripts']);
  for(const f of await walk(path.join(root,'astro-site/public')))if(f.endsWith('.html')&&path.basename(f)!=='google55b1c42743aa7ee2.html')throw new Error('Raw HTML in public/ bypasses shared generation: '+f);
  run('npm',['--prefix','astro-site','run','build']);
  run('npm',['--prefix','astro-site','run','test:output']);
  const expectedRoutes=routes();
  for(const p of expectedRoutes){const rel=path.join(p.locale==='ja'?'':p.locale,p.route,'index.html');const html=await readFile(path.join(dist,rel),'utf8');assertShared(html,rel);}
  const origins=[['https://rm-referral.maffun.workers.dev','https://mnp-navi.jp'],...locales.filter(l=>l!=='ja').map(l=>['https://rm-referral-'+l+'.maffun.workers.dev','https://mnp-navi.jp/'+l])];
  for(const f of await walk(dist)){if(!/\.(html|xml|txt|js|json)$/.test(f))continue;let html=await readFile(f,'utf8');for(const [a,b] of origins)html=html.replaceAll(a,b);
   const first=path.relative(dist,f).split(path.sep)[0];if(f.endsWith('.html')&&locales.includes(first))html=await localizeNavigation(html,first,dist);
   await writeFile(f,html);
  }
  const manifest={version:1,input,createdAt:new Date().toISOString(),pages:expectedRoutes.length,files:{}};
  const publicHtml=new Set(expectedRoutes.map(p=>path.join(p.locale==='ja'?'':p.locale,p.route,'index.html')));
  publicHtml.add('google55b1c42743aa7ee2.html');
  for(const l of locales.filter(l=>l!=='ja'))publicHtml.add(l+'/google55b1c42743aa7ee2.html');
  for(const l of locales){const target=path.join(release,l);await rm(target,{recursive:true,force:true});await mkdir(target,{recursive:true});
   for(const f of await walk(dist)){const rel=path.relative(dist,f),first=rel.split(path.sep)[0];if(l==='ja'?locales.includes(first):first!==l)continue;if(f.endsWith('.html')&&!publicHtml.has(rel))continue;
    const to=path.join(target,rel);await mkdir(path.dirname(to),{recursive:true});await cp(f,to);
   }
   manifest.files[l]=await Promise.all((await walk(target)).map(async f=>({file:path.relative(target,f),sha256:hash(await readFile(f))})));
  }
  if(await fingerprint()!==input)throw new Error('Sources changed during build; refusing to publish');
  await writeFile(receiptFile,JSON.stringify(manifest)+'\n');await verifyReceipt(input);
  console.log('Shared-component release verified: '+expectedRoutes.length+' pages / 6 languages');
 }finally{await rm(lock,{recursive:true,force:true});}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await prepareRelease();
